name = "sbs-normalizer"
main = "src/index.ts" # Required but ignored for containers
compatibility_date = "2024-04-01"

[[containers]]
image = "registry.cloudflare.com/d7b99530559ab4f2545e9bdc72a7ab9b/sbs-normalizer-service:v1"
class_name = "SBSNormalizer"

[[durable_objects.bindings]]
name = "SBS_NORMALIZER"
class_name = "SBSNormalizer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SBSNormalizer"]
